# Generated by Django 5.1.7 on 2025-03-09 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='entry',
            field=models.TextField(blank=True, null=True),
        ),
    ]
